server.port=${SERVER_PORT:8080}
spring.application.name=${NAME:api-post}
spring.datasource.url=${DB_URL:jdbc:postgresql://api_post_prueba_user:FrX0SesrfoiPGAjJWr54LZz3FlcX5Cyv@dpg-d76mhc9aae7s73clul6g-a/api_post_prueba}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:123456789}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 
#Muestra las consultas en la consola 
# Formatea el SQL en la consola para que sea legible
spring.jpa.properties.hibernate.format_sql=true